name: build and upload image

on:
  pull_request:
    types:
      - labeled
      - closed
    branches:
      - main  # Adjust this to the appropriate branch name

jobs:
  build_and_upload:
    name: Build and Upload image
    runs-on: ubuntu-latest
  
    if: >
      github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:TriggerBuild')
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Submodule init
      run: |
        git submodule init
        git submodule update

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Setup
      run: |
        wget https://de012a78750e59b808d922b39535e862.s3.eu-west-1.amazonaws.com/v1.1.0-rc.1-fork.4.tgz
        tar -xzvf v1.1.0-rc.1-fork.4.tgz
        rm -rf config
        mv v1.1.0-rc.1-fork.4/config .
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: zkevm-prover
        IMAGE_TAG: latest
      run: |
        docker build -f Dockerfile-GHA -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
