name: build and upload image

on:
  pull_request:
    types:
      - labeled
      - closed
    branches:
      - main  # Adjust this to the appropriate branch name

jobs:
  build_and_upload:
    name: Build and Upload image
    runs-on: ubuntu-latest
  
    if: >
      github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:TriggerBuild')
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set variables
      id: setvars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Submodule init
      run: |
        git submodule init
        git submodule update

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Executor
      id: docker_build_executor
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-GHA
        platforms: linux/amd64
        push: true
        target: executor
        tags: |
            104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkevm-prover:${{ steps.setvars.outputs.tag }}
            104047360514.dkr.ecr.eu-central-1.amazonaws.com/zkevm-prover:${{ steps.setvars.outputs.sha_short }}
